apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-dep
  labels:
    app: web-dep
spec:
  replicas: 5
  selector:
    matchLabels:
      app: web-pod
  template:
    metadata:
      labels:
        app: web-pod
    spec:
      containers:
        - name: app
          image: nginx
          ports:
            - containerPort: 80